# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            marciogm
tagline:          'codes'
description:      'codes'
url:              http://www.marciogm.com.br
baseurl:          /

author:
  name:           'Marcio Giaxa Marinheiro'
  url:            https://twitter.com/marciogm

paginate:         5

# Custom vars
version:          2.1.0

github:           http://www.github.com/marciogm
